service: screenshuttle

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  capture:
    handler: handler.capture
    events:
      - http:
          path: capture
          method: get
          cors: true

package:
  exclude:
    - node_modules/**
  include:
    - node_modules/puppeteer-core/**
    - node_modules/chrome-aws-lambda/**
