AWSTemplateFormatVersion: 2010-09-09
Description: LambdaSAM deployment stack.
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: Project/ecr repositroy name.
    Default: screenshuttle
  ImageTag:
    Type: String
    Description: Image tag for the image to be deployed. Keep this as commit id to ensure cfn records the change during deployment
    Default: commit-id-here

Resources:
  ScreenshuttleLambda:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 150
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.eu-west-1.amazonaws.com/${ProjectName}:${ImageTag}"
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - Statement:
            - Effect: Allow
              Action:
                - ecr:BatchGetImage
                - ecr:GetDownloadUrlForLayer
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:repository/${ProjectName}"
      SnapStart:
        ApplyOn: None

Outputs:
  FunctionName:
    Description: Function name for
    Value: !Ref ScreenshuttleLambda
    Export:
      Name: !Join ["-", [!Ref ProjectName, function]]