AWSTemplateFormatVersion: 2010-09-09
Description: LambdaSAM deployment stack.
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Description: Project/ecr repositroy name.
    Default: screenshuttle

Resources:
  ScreenshuttleLambda:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Timeout: 3
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.eu-west-1.amazonaws.com/${ProjectName}:main"
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - Statement:
            - Effect: Allow
              Action:
                - ecr:BatchGetImage
                - ecr:GetDownloadUrlForLayer
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:repository/${ProjectName}"
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /screenshuttle
            Method: POST
